#!/bin/bash
# install pureftp
# centos 7, centos 8, debian and ubuntu supported
# todo allow sudo instead of just using root

echo "install pureftp";

#HAS_SUDO=$(sudo -n -v 2>&1);test -z "$A" || echo $A|grep -q asswor;
#echo HAS_SUDO;

#change username and password here
user='pureftpuser';
password='pureftpuserpassword';

full_path=$(realpath $0);
dir_path=$(dirname $full_path);

# check if user is root
if [[ $EUID -ne 0 ]]; 
   then
      # user is not root
      echo "This script must be run as root";
      exit 1;
   else
      # user is root
      :
fi

if [ -x "$(command -v apt)" ]; then
  apt update -y;
  apt upgrade -y;
  apt install dnsutils -y;
  apt install pure-ftpd -y;
  apt install openssl -y;
elif [ -x "$(command -v yum)" ]; then
  yum update -y;
  yum upgrade -y;
  yum install bind-utils -y;
  yum install pure-ftpd -y;
  yum install openssl -y;
elif [ -x "$(command -v dnf)" ]; then
  dnf update -y;
  dnf upgrade -y;
  dnf install bind-utils -y;
  dnf install pure-ftpd -y;
  dnf install openssl -y;
else
  :
fi

#systemctl status pure-ftpd;
useradd -m $user;
echo -e "$password\n$password" | passwd $user;

mkdir -p /etc/ssl/private/;
subj="/C=BB/ST=State/L=Country/O=Organization/OU=Department/CN=$(hostname)/emailAddress=webmaster@$(hostname)";
openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem -days 365 -subj "$subj";
yes | sudo cp --backup=numbered /etc/pure-ftpd/pure-ftpd.conf /etc/pure-ftpd/pure-ftpd.conf.bak;

# TLS 1: FTP and TLS
# TLS 2: only TLS
# TLS 3: only FTP
if sudo grep -Fq '# TLS                          1' /etc/pure-ftpd/pure-ftpd.conf
then
   sed -i 's/\# TLS                          1/TLS                          1/g' /etc/pure-ftpd/pure-ftpd.conf
else
   :
fi
if sudo grep -Fq '# TLSCipherSuite               HIGH' /etc/pure-ftpd/pure-ftpd.conf
then
   sed -i 's/\# TLSCipherSuite               HIGH/TLSCipherSuite               HIGH:MEDIUM:+TLSv1:!SSLv2:!SSLv3/g' /etc/pure-ftpd/pure-ftpd.conf
else
   :
fi
if sudo grep -Fq '# CertFile                     /etc/ssl/private/pure-ftpd.pem' /etc/pure-ftpd/pure-ftpd.conf
then
   sed -i 's/\# CertFile                     \/etc\/ssl\/private\/pure-ftpd.pem/CertFile                     \/etc\/ssl\/private\/pure-ftpd.pem/g' /etc/pure-ftpd/pure-ftpd.conf
else
   :
fi

# some instalations /etc/pure-ftpd/conf does not work
mkdir -p /etc/pure-ftpd/conf;
touch /etc/pure-ftpd/conf/TLS;
echo 1 > /etc/pure-ftpd/conf/TLS;

touch /etc/pure-ftpd/conf/ChrootEveryone;
echo YES > /etc/pure-ftpd/conf/ChrootEveryone;

systemctl restart pure-ftpd;
systemctl status pure-ftpd;

cd $dir_path;
