#!/bin/bash
# install node
add_to_path()
{
    if [[ "$PATH" =~ (^|:)"${1}"(:|$) ]]
    then
        echo ${1} exists in PATH=\"$PATH\";
        return 0;
    fi
    yes | cp --backup=numbered ~/.bash_profile ~/.bash_profile.bak;
    sed -i '/export PATH/d' ~/.bash_profile;
    echo "export PATH=$PATH:${1}" >> ~/.bash_profile;
    source ~/.bash_profile;
}
echo "install node";
node_file="nodejs.tar.gz";
cd ~
mkdir bin
cd bin
rm -f node
rm -f npm
rm -rf nodejs
wget -r -nd -l1 --no-parent -e robots=off -A "*linux-x64.tar.gz" https://nodejs.org/dist/latest/
mv node*linux-x64.tar.gz $node_file
tar -xvf $node_file;
rm -f ./$node_file;
mv node*linux-x64 nodejs
cp ./nodejs/bin/node ~/bin;
ln -s ./nodejs/lib/node_modules/npm/bin/npm-cli.js npm;
add_to_path $(pwd);
node --version;
npm --version;
echo type "source ~/.bash_profile";

