#!/bin/bash
# install csf
# todo allow sudo instead of just using root

echo "install csf";

full_path=$(realpath $0);
dir_path=$(dirname $full_path);

# check if user is root
if [[ $EUID -ne 0 ]]; 
   then
      # user is not root
      echo "This script must be run as root";
      exit 1;
   else
      # user is root
      :
fi

mkdir -p ~/csf/
cd ~/csf/
wget http://download.configserver.com/csf.tgz
tar xzf csf.tgz
cd csf
sh install.sh
yes | sudo cp --backup=numbered /etc/csf/csf.conf /etc/csf/csf.conf.bak
sed -i 's/DENY_IP_LIMIT = "200".*/DENY_IP_LIMIT = "9000"/g' /etc/csf/csf.conf
sed -i 's/DENY_TEMP_IP_LIMIT = "100".*/DENY_TEMP_IP_LIMIT = "9000"/g' /etc/csf/csf.conf
sed -i 's/TESTING = "1"/TESTING = "0"/g' /etc/csf/csf.conf
sed -i 's/TCP_IN = .*/TCP_IN = "20,21,22,25,53,80,110,143,443,465,587,993,995"/g' /etc/csf/csf.conf
sed -i 's/TCP_OUT = .*/TCP_OUT = "20,21,22,25,53,80,110,113,443,587,993,995,3306,4083"/g' /etc/csf/csf.conf
sed -i 's/UDP_IN = .*/UDP_IN = "20,21,53"/g' /etc/csf/csf.conf
sed -i 's/UDP_OUT = .*/UDP_OUT = "20,21,53,113,123"/g' /etc/csf/csf.conf

yes | sudo cp --backup=numbered /etc/csf/csf.blocklists /etc/csf/csf.blocklists.bak
sed -i 's/#SPAMEDROP/SPAMEDROP/g' /etc/csf/csf.blocklists
sed -i 's/#CIARMY/CIARMY/g' /etc/csf/csf.blocklists
sed -i 's/#BFB/BFB/g' /etc/csf/csf.blocklists

systemctl enable csf
systemctl enable lfd
systemctl restart csf
systemctl restart lfd

cd $dir_path;
