#!/bin/bash
# install composer
# Note: Multiple versions of PHP had to be disabled inorder for the composer instalation to work.
# need to fix

full_path=$(realpath $0);
dir_path=$(dirname $full_path);

echo "install composer";

composer_url="https://getcomposer.org/installer";
mkdir -p "/home/$USER/bin";
cd "/home/$USER/bin";
wget $composer_url;
php -d allow_url_fopen=On installer -check;
php installer;
rm -f installer;
mv composer.phar composer;
sed -i '/alias composer=.*/d' ~/.bashrc;
echo 'alias composer="php -d allow_url_fopen=On /home/$USER/bin/composer"' >> ~/.bashrc;
source ~/.bashrc;
cd $dir_path;
exec bash;
#bash --login;
composer self-update;
composer -V;
